PRINT N'Populate RefEducationLevel table';
IF EXISTS(SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[RefEducationLevel]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01043', 'No school completed ', 'No school completed is the extent of formal instruction a person has received.', 0.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00788', 'Preschool ', 'Preschool is the extent of formal instruction a person has received.', 1.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00805', 'Kindergarten ', 'Kindergarten is the extent of formal instruction a person has received.', 2.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00790', 'First grade ', 'First grade is the extent of formal instruction a person has received.', 3.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00791', 'Second grade ', 'Second grade is the extent of formal instruction a person has received.', 4.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00792', 'Third grade ', 'Third grade is the extent of formal instruction a person has received.', 5.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00793', 'Fourth grade ', 'Fourth grade is the extent of formal instruction a person has received.', 6.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00794', 'Fifth grade ', 'Fifth grade is the extent of formal instruction a person has received.', 7.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00795', 'Sixth grade ', 'Sixth grade is the extent of formal instruction a person has received.', 8.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00796', 'Seventh grade ', 'Seventh grade is the extent of formal instruction a person has received.', 9.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00798', 'Eighth grade ', 'Eighth grade is the extent of formal instruction a person has received.', 10.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00799', 'Ninth grade ', 'Ninth grade is the extent of formal instruction a person has received.', 11.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00800', 'Tenth grade ', 'Tenth grade is the extent of formal instruction a person has received.', 12.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00801', 'Eleventh Grade ', 'Eleventh Grade is the extent of formal instruction a person has received.', 13.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01809', '12th grade, no diploma ', '12th grade, no diploma is the extent of formal instruction a person has received.', 14.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01044', 'High school diploma ', 'High school diploma is the extent of formal instruction a person has received.', 15.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('02408', 'High school completers (e.g., certificate of attendance) ', 'High school completers (e.g., certificate of attendance) is the extent of formal instruction a person has received.', 16.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('02409', 'High school equivalency (e.g., GED) ', 'High school equivalency (e.g., GED) is the extent of formal instruction a person has received.', 17.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00803', 'Grade 13', 'Grade 13is the extent of formal instruction a person has received.', 18.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('00819', 'Career and Technical Education certificate', 'Career and Technical Education certificate is the extent of formal instruction a person has received.', 18.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01049', 'Some college but no degree ', 'Some college but no degree is the extent of formal instruction a person has received.', 19.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01047', 'Formal award, certificate or diploma (less than one year) ', 'Formal award, certificate or diploma (less than one year) is the extent of formal instruction a person has received.', 20.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01048', 'Formal award, certificate or diploma (more than or equal to one year) ', 'Formal award, certificate or diploma (more than or equal to one year) is the extent of formal instruction a person has received.', 21.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01050', 'Associate''s degree (two years or more) ', 'Associate''s degree (two years or more) is the extent of formal instruction a person has received.', 22.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73063', 'Adult education certification, endorsement, or degree', 'Adult education certification, endorsement, or degree is the extent of formal instruction a person has received.', 22.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01051', 'Bachelor''s (Baccalaureate) degree ', 'Bachelor''s (Baccalaureate) degree is the extent of formal instruction a person has received.', 24.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01054', 'Master''s degree (e.g., M.A., M.S., M. Eng., M.Ed., M.S.W., M.B.A., M.L.S.) ', 'Master''s degree (e.g., M.A., M.S., M. Eng., M.Ed., M.S.W., M.B.A., M.L.S.) is the extent of formal instruction a person has received.', 25.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01055', 'Specialist''s degree (e.g., Ed.S.) ', 'Specialist''s degree (e.g., Ed.S.) is the extent of formal instruction a person has received.', 26.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73081', 'Post-master’s certificate', 'Post-master’s certificate is the extent of formal instruction a person has received.', 26.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01052', 'Graduate certificate ', 'Graduate certificate is the extent of formal instruction a person has received.', 27.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01057', 'Doctoral (Doctor''s) degree ', 'Doctoral (Doctor''s) degree is the extent of formal instruction a person has received.', 28.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01053', 'First-professional degree ', 'First-professional degree is the extent of formal instruction a person has received.', 29.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('01056', 'Post-professional degree ', 'Post-professional degree is the extent of formal instruction a person has received.', 30.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73082', 'Doctor’s degree-research/scholarship', 'Doctor’s degree-research/scholarship is the extent of formal instruction a person has received.', 31.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73083', 'Doctor’s degree-professional practice', 'Doctor’s degree-professional practice is the extent of formal instruction a person has received.', 31.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73084', 'Doctor’s degree-other', 'Doctor’s degree-other is the extent of formal instruction a person has received.', 31.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('73085', 'Doctor’s degree-research/scholarship', 'Doctor’s degree-research/scholarship is the extent of formal instruction a person has received.', 31.00, 1)
INSERT INTO dbo.[RefEducationLevel]([Code], [Description], [Definition], [SortOrder], [RefEducationLevelTypeId])
VALUES ('09999', 'Other', 'The extent of formal instruction a person has received is in a category not yet defined in CEDS.', 32.00, 1)
END;